const data = {
  products: [
    {
      _id: '1',
      name: 'Nike black shoe',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 5,
      brand: 'Nike',
      rating: 4,
      numReviews: 10,
      description: 'High quality product',
    },

    {
      _id: '2',
      name: 'Nike black shoe',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 0,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      _id: '3',
      name: 'Nike black shoe',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 5,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      _id: '4',
      name: 'Nike black shoe',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 5,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      _id: '5',
      name: 'Nike black shoe',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 420,
      countInStock: 5,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      _id: '6',
      name: 'Nike black shoe',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 5,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
  ],
}
export default data
