import bcrypt from 'bcryptjs'

const data = {
  users: [
    {
      name: 'mmislam',
      email: 'mmislam272@gmail.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'anyone',
      email: 'user@gmail.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Nike black shoe',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 5,
      brand: 'Nike',
      rating: 4,
      numReviews: 10,
      description: 'High quality product',
    },

    {
      name: 'Nike black shoe',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 0,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      name: 'Nike black shoe',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 5,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      name: 'Nike black shoe',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 5,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      name: 'Nike black shoe',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 420,
      countInStock: 5,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      name: 'Nike black shoe',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 5,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
  ],
}
export default data
